### ISSUE TITLE
Error when trying to rebase the tree to vauxite

### ISSUE THREAD

**Issue by Foxsterx3** [hyperreal64/ostree-vauxite-desktop#1]
When launching the command
" rpm-ostree rebase hyperreal:vauxite-desktop "
Give me this error:
error: While pulling vauxite-desktop: While fetching https://ostree.hyperreal.coffee/summary.sig: [6] Couldn't resolve host name

**Comment by hyperreal64** [comment]
My apologies, I no longer maintain this.

Feel free to use this repository as a basis for your own project. You could even run the compose.sh script locally, and have a simple web server setup on your local machine that serves the remote.

**Comment by kayomn** [comment]
May be worth archiving the repo and marking this as no longer maintained, was trying to troubleshoot for a while until coming to here.

**Comment by hyperreal64** [comment]
> May be worth archiving the repo and marking this as no longer maintained, was trying to troubleshoot for a while until coming to here.

It seems this project has more users than I realized. In light of this, I will continue to maintain it. I'll report back here when everything is back in order. Thanks for your input!

**Comment by hyperreal64** [comment]
Okay, so everything is back in order. The remote's URL is slightly different now, so you'll have to remove the old one, add the new one, and rebase.

```shell
# remove old remote
sudo ostree remote delete hyperreal

# add new remote
sudo ostree remote add --no-gpg-verify hyperreal https://ostree.hyperreal.coffee/vauxite-desktop

# rebase
rpm-ostree rebase hyperreal:vauxite-desktop
```

You may not have to completely rebase, because the remote has the same name, so you might be able to just run `rpm-ostree update`.

Please let me know if you run into any issues! Thank you.

**Comment by kayomn** [comment]
Installed to a VM to test before installing back onto hardware and everything seem to be in order, so I think it's safe to close this as resolved.

**Comment by hyperreal64** [comment]
> Installed to a VM to test before installing back onto hardware and everything seem to be in order, so I think it's safe to close this as resolved.

Awesome, thanks for reporting back. I'm very sorry about the inconvenience this caused. I don't use Xfce currently as I'm running Fedora Silverblue, but I'm going to keep a pet Vauxite VM to enable me to better troubleshoot errors and such.
