### ISSUE TITLE
Various software missing from base deployment

### ISSUE THREAD

**Issue by kayomn** [hyperreal64/ostree-vauxite-desktop#2]
Standard XFCE tools like Mousepad and Engrampa are missing from the distribution. I have been layering these packages for a while, but I believe that is only band-aiding the issue.

Additionally, non-standard software like the Caja file manager is deployed as part of the desktop alongside the XFCE-default Thunar.

I had a look through the image configs and it looks like Caja only appears in the Mate file, but somehow it is making its way into the XFCE deployment. In fact, the Vauxite config also lists Ristretto, however that is also not deployed.

**Comment by kayomn** [comment]
Correction: I've realized that `fedora-vauxite.yaml` is not what is deployed but instead `vauxite-desktop.yaml`.

That explains the absence of Mousepad and Engrampa, so I'll continue layering those, however I'm still unsure as to what is causing Mate's Caja file manager to be packaged as well.

**Comment by kayomn** [comment]
Figured it out - Caja is being installed as a dependency of Engrampa. Mark that as a user error.

This issue can be closed if supplying Mousepad as part of the base image is beyond the scope of this Silverblue spin, however IIRC it is supplied standard with the regular Fedora spin and isn't on Flathub.

**Comment by hyperreal64** [comment]
Thanks for your input! Mousepad can be installed from Flathub with `flatpak install org.xfce.mousepad`. The Ristretto image viewer is also available on Flathub. Those are the only Xfce apps on Flathub that I'm aware of. I don't know how often these Flathub apps are updated, so if you find that they are outdated then I can see about adding them to the base image. Mousepad is a light package so it shouldn't increase build time too much.

**Comment by kayomn** [comment]
That resolves Mousepad and Ristretto - thanks.

It would probably make sense to ship an archiving tool with the image as the archive options in context menu plugin for Thunar is currently packaged. Alternatively, you could drop the archiver plugin from the base image if you don't want to.

Otherwise, right-clicking and trying to extract is currently broken and requires manual user fixing by installing a Flatpak and setting `flatpak run org.company.archiver` as the execute path for the archiving tool.

**Comment by hyperreal64** [comment]
Ah, thanks for letting me know about the missing archiving tool. I've added xarchiver to the base image. It should be available in the next build on 2022-12-17.

**Comment by kayomn** [comment]
Updated and xarchiver is available, closing.
